### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by musti156** [ncravino/H96_MAX_V58#2]
Have this box. Wifi doesn't work have flashed every firmware image I can find. Ethernet works for about 5 minutes after firmware installation then drops out doesn't come back online. Desperate for a fix from developer or if anyone else can help.

**Comment by ncravino** [comment]
Hi! Have you tried the manufacturer image (from here: https://www.h96tvbox.com/firmware-download/)? If so, then probably your box has some hardware issue.

**Comment by musti156** [comment]
Thank you. I have managed to resolve my issue. There's is a new dated firmware that unfortunately isn't linked on the website.

**Comment by ghost** [comment]
> Have this box. Wifi doesn't work have flashed every firmware image I can find. Ethernet works for about 5 minutes after firmware installation then drops out doesn't come back online. Desperate for a fix from developer or if anyone else can help.

Do you know what this firmware do? H96 Max V58 RK3588 20230728.1802
