### ISSUE TITLE
flashing Mekotronics R58 rom to H96 v58 possible?

### ISSUE THREAD

**Issue by manaboy** [ncravino/H96_MAX_V58#3]
Nice research on the H96 V58 RK3588 box,  I have this box and although it has the same hardware as Mekotronics R58, it runs at a lower clock speed. I was looking for a custom kernel that allows to set cook speed to the same as the Mekotronics R58. Any infor on this?. I think this box can't be bricked as it has a built in USB flasher.

Regards

**Comment by ncravino** [comment]
I haven't checked the Mekotronics R58. You might able to do it via abd and setting stuff in /sys/devices/system/cpu/cpu*/ scaling freq and governor files (similar way to how it its done in linux). Note that the cooling on the box is not that good, so it might get throttled down anyway.
