### ISSUE TITLE
advice on updating Graphics drivers 

### ISSUE THREAD

**Issue by manaboy** [ncravino/H96_MAX_V58#4]
So the box is indeed easily rooted with magisk to gain root access and super user, the question is, I las firmware update for this box was Version:20221116.1404 as found at thr following link [https://www.h96tvbox.com/firmware-download/](url)

I found a newer firmware then that on some Russian website but didn't find any info on what was updated.

The current GPU driver often gives VK_Lost error. I know Google pixel has a more up to date GPU driver however I am not sure if that will be compatible.

There's also development of drivers etc from the soc at the following

[https://github.com/industrialtablet/RK3588-Development-Board/blob/main/RK3588_Update_Firmware.md](url)

Not sure if the driver is any better, I'm not really wellversed when it comes to Android.

Hoping to get some advice.

I recently installed an active pwm fan with controller to this TV box to keep it cooled down and have made it somewhat an emulating machine, it's amazing how it's able to perform pretty good using only 7 Watts in comparison my Ryzen 7 5700G Apu is not as good using igpu and that's with 70watts.

No other community forum exist for this particular TV box, hope to get some support, advice.

I didn't find a discussion channel on this GitHub so my apologies if I should have not posted it as an issue.

Thanks

**Comment by manaboy** [comment]
Ota update isn't updating and says (already up to date) but I found that the firmware is being updated with the last update November 2023 at the following link, it has userdebug TableTest
[https://chinagadgetsreviews.com/?s=%22H96+Max+V58%22](url)

**Comment by ncravino** [comment]
I've yet to restart my tests on this box (due to lack of time) but I can say:
- I believe Pixel driver will hardly be compatible as GPU drivers tend to be very SoC specific
- These boxes tend to have some bugs on their firmware, the one you refer is related to vulkan, perhaps try other older firmware to see if it's there?
